export const AuthNav = {
  HOME: 'Home',
  LOGIN: 'Login',
  SIGN_UP: 'SIGN_UP',
  SPLASH_SCREEN: 'SplashScreen',
  TAB_NAV: 'TabNav',
  ROOT_NAV: 'RootNav',
  CATEGORIES: 'CATEGORIES',
  DETAIL_NEWS: 'DetailNews',
  INFORMATION_INNKEEPER: 'INFORMATION_INNKEEPER',
  MY_ACCOUNT: 'MY_ACCOUNT',
  MESSAGE: 'MESSAGE',
  SELECT_POSITION_SCREEN: 'SELECT_POSITION_SCREEN',
};
